### ISSUE TITLE
NegativeArraySizeException when there's too many rows

### ISSUE THREAD

**Issue by avargaz** [clytras/AccessConverter#8]
I have a DB with more than 2 million of rows and I get a:
Is there a way to split the output in multiple json files?

```
Exception in thread "main" java.lang.NegativeArraySizeException: -1955501104
        at java.base/java.lang.StringCoding.encodeUTF8(StringCoding.java:904)
        at java.base/java.lang.StringCoding.encode(StringCoding.java:449)
        at java.base/java.lang.String.getBytes(String.java:983)
        at org.apache.commons.io.IOUtils.write(IOUtils.java:1857)
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1982)
        at org.apache.commons.io.FileUtils.write(FileUtils.java:2107)
        at org.apache.commons.io.FileUtils.write(FileUtils.java:2125)
        at org.apache.commons.io.FileUtils.write(FileUtils.java:2090)
        at accessconverter.AccessConverter.Run(AccessConverter.java:151)
        at accessconverter.AccessConverter.main(AccessConverter.java:76)
```

**Comment by clytras** [comment]
Hey @avargaz,
I know It's been a while since you posted this issue, but I have published a new release with several performance improvements and I would like to tackle this and make the converter work with huge datasets.
You can try it if you have time and will.
